### ISSUE TITLE
Client for Zotero API

### ISSUE THREAD

**Issue by jshoyer** [ropensci-archive/wishlist#10]
By direct analogy to the RMendeley package.
Maybe there would even be utility in an R wrapper for the related Citation Style Language.

Docs: https://www.zotero.org/support/dev/web_api/v3/start
- Note that Python/PHP/Objective-C implementations could potentially be ported

It may be possible to get some help via the zotero-dev mailing list or https://forums.zotero.org/

I will try to work on this (or at least add detail to this issue) as time allows. I have read #2 and #3, but I have refrained from adding this issue to the wiki page because that page seems redundant to me.

**Comment by karthik** [comment]
I believe @sckott already wrote something for CSL. Can you say more about the kinds of metrics or use cases for the Zoerto API data? Do we get details on readership and such?

**Comment by sckott** [comment]
**WRT CSL** 

I work on a client for CSL styles and locales - https://github.com/ropensci/csl#csl - This client retrieves and loads locales and CSL styes - that's all it's meant to do. 

I was planning on writing another package as a proper CSL processor, like https://github.com/brechtm/citeproc-py for python

I don't think there's much need for CSL style creation utilities in R, but perhaps I'm wrong?

@jshoyer what of the above things I listed did you have in mind? or something else?

**Comment by jshoyer** [comment]
Hi @sckott, I did not have anything else in mind---that was a last minute idea, and I had not seen your package.

I'll look into metrics---they may only be possible for Public Open Membership groups (one of three kinds of groups---see https://www.zotero.org/support/groups)

**Comment by dfalster** [comment]
Would be great if we could query and push data via Zotero API. I raised similar idea some years back, @sckott already wrote me a function for fetching data (see PR [here](https://github.com/dfalster/RZotero/commit/b5b53a4c13354d3f2444e3c592785e4cc2e40f75)). I never got around to developing this any further, but next step would be add option to push data. 

My major use cases for this would be:
1. Cleaning my library using combination of Zotero API and other tools: add missing dois, abstracts, clean journal names, add / remove tags (all things that would be nice to have in zotero itself but show little signs of appearing)
2. Download reference lists from particular folders in bibtex format

**Comment by karthik** [comment]
> I don't think there's much need for CSL style creation utilities in R, but perhaps I'm wrong?
> @sckott Doesn't seem like it because even with the current workflow that many of us use, R doesn't need to deal with these.

@dfalster Great use cases! Seems like there is enough interest and momentum to kick this off. @jshoyer If you (or anyone else) want to take the lead, the rest of us can pitch in and build this up. Given the current status of how packages are accepted into rOpenSci, it would be best for you to start a repo under your account that we can contribute to. Once it's ready we can onboard it into rOpenSci. How does that sound?

**Comment by dfalster** [comment]
I tidied up my existing RZotero repo (deleted some large files from history, simplified). That contains Scott's code and is ready to go. Happy for repo to live where it is or move. 
https://github.com/dfalster/RZotero

**Comment by mbojan** [comment]
Hi! 

This is an old item, but still open so perhaps you are still interested @sckott @karthik and others?

Being a heavy Zotero user myself and having to write some RMarkdown-powered research papers (... and not without a grain of COVID-induced procrastination...) I wrote https://github.com/mbojan/zoterro . It uses the current Zotero API version 3. 

My personal need was to fetch manuscript-related entries to a local `.bib` file that is used by `Rmd` file. Not all API endpoints have their R counterparts at this moment but the low-level `zotero_api()` can be used to access any endpoint with proper credentials in the header and ability to make multiple requests if the request results do not fit a single response.

I encourage all of you interested in developing it further to jump-in.

I will be happy to enter the rOpenSci on-boarding process as soon as it picks-up from the pandemic lethargy.

**Comment by sckott** [comment]
Nice, glad to hear @mbojan  thanks for pinging the community here !

**Comment by maelle** [comment]
Note that there's also https://github.com/eblondel/zen4R (no idea what API version it covers :-))

**Comment by mbojan** [comment]
But this is for Zenodo not Zotero, right?

wt., 2 cze 2020, 13:26 użytkownik Maëlle Salmon <notifications@github.com>
napisał:

**Comment by maelle** [comment]
OOPS, my bad!!

**Comment by dfalster** [comment]
Great to hear you're working on this @mbojan. As noted in thread above, I started a repo for working with Zotero (https://github.com/dfalster/RZotero) but never got very far. Some of the stuff there may be useful. I tried your package out and it works. I'm keen to contribute, even if only for testing. Btw - I love your package name and logo!

**Comment by mbojan** [comment]
Thanks @dfalster! Covering the search endpoints of the API, that you started in your code, will probably have high priority, right after handling the caching and rate limits (although, it seems, the latter are not yet enforced by Zotero). Contributors are more than welcome!

**Comment by dfalster** [comment]
Cool. But for the record, @sckott wrote the search stuff :)

**Comment by maelle** [comment]
Thank you!

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
