### ISSUE TITLE
Static code analysis

### ISSUE THREAD

**Issue by e-pet** [ropensci-archive/wishlist#11]
It would be nice to have a decent tool for static code analysis.

This could run automatically during the build process and detect errors early on, before they cause trouble, and with possibly easier to decipher warning/error mesages.

Citing [an earlier question of mine on StackOverflow](http://stackoverflow.com/questions/24741236/is-there-any-static-code-analysis-tool-for-r-other-than-codetools):

> The only static code analysis tool I was able to find is codetools. Searching for more information, however, only yields
> - [The packages CRAN page](http://cran.r-project.org/web/packages/codetools/index.html), stating that the last release is from 2011 and providing a very minimalistic documentation aswell as the code itself, which starts with the note "This code is a complete hack, may or may not work, etc.." and indeed looks like a quick hack.
> - [A short, apparently academic presentation](http://homepage.stat.uiowa.edu/~luke/talks/DSC07.pdf) by the package author, Luke Tierney, from 2007.
> - [The author's website](http://homepage.stat.uiowa.edu/~luke/), which however does not provide any further information on the subject (except for the above presentation).
> - [An obscure blog entry](http://yusung.blogspot.de/2008/02/r-package-codetools.html) indicating that "Since the release of R_2.6.0, R package developers were advised to use the ``codetools" package to check potential bugs.".
> 
> So, apparently, there have been no updates for a long time; it is not easily possible to contribute to the project (there is no git repository or something and the code is difficult to read) and there is no real documentation of what it does. Still, it is used by default for checking CRAN packages. Now that's weird?

In particular the referenced presentation shows some of the potential benefits that static code analysis could provide for R. It would be more of a general tool for use mainly by package authors to improve general code quality.

I am just suggesting this, as I really don't have time for such a project right now (and I'm not really an expert in static code analysis). I think, this would make for a great thesis project for computer science students, by the way.

**Comment by ashander** [comment]
See [lintr](https://github.com/jimhester/lintr) from @jimhester

**Comment by jimhester** [comment]
Most of the `lintr` checks are geared towards style rather than function.  However it does use the static code checks from `codetools` in the  [object_usage_linter](https://github.com/jimhester/lintr/blob/b34e1fdc0c6ff6a456d98d4d5573ae35d6605b11/R/object_usage_linter.R) (and you can turn off the style linters individually if you don't want to use a given one).

I would be happy to incorporate more static analysis linters in `lintr` as well, so if you have ideas or implementations please open issues/send pull requests.

**Comment by jennybc** [comment]
This reminds me. Back when I was a PhD student, I (!!!) actually wrote a lot of C. I used something to analyze all of my own code. Which functions called which others, which header files were used where, which libraries I was linking to and from where, etc etc. It actually generated a beautiful cross-referenced report, with LaTeX, I believe. Can anyone tell me what that tool might have been?

And once we get the name, let's add it as inspiration for this! Agree this would be great for developing R packages.

**Comment by Ironholds** [comment]
Jenny "Close to the Metal" Bryan. It fits!

I'd love to see that tool - as you say, it'd be great to adopt formats from other languages that have been wrestling with/thinking about this problem for a while.

**Comment by ashander** [comment]
@jimhester thanks for clarifying. I should have been clear in my curt comment that lintr isn't a solution to the general problem. great, useful package by the way!

@jennybc that sounds like a great tool. Any chance [wiki's list of static code analysis tools](http://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B) jogs your memory?

**Comment by maelle** [comment]
Thank you! see also recent work by @mpadge in https://github.com/ropensci-review-tools/pkgcheck & co

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
