### ISSUE TITLE
A Qualtrics package + Shiny dashboard

### ISSUE THREAD

**Issue by karthik** [ropensci-archive/wishlist#15]
Many of us use Qualtrics for scientific surveys. Right now accessing results is a bit cumbersome and it is hard to share credentials among several folks. 
However, with their API, it would be nice to have a R package where one could use a key (possibly even encrypted) so many folks (say instructors and such) can access survey results via a companion shiny app.

old Qualtrics package: https://github.com/jbryer/qualtrics
Qualtrics API documentation: http://www.qualtrics.com/university/researchsuite/developer-tools/api-integration/qualtrics-rest-api/

I don't have time to take this on right now (might at a later time) but this would be useful across the board to various researchers.

cc @tracykteal

**Comment by maelle** [comment]
Thank you! There's docs.ropensci.org/qualtRics now

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
