### ISSUE TITLE
Template for a html version of RStudio's cheatsheets

### ISSUE THREAD

**Issue by sckott** [ropensci-archive/wishlist#16]
RStudio provides [cheatsheets](http://www.rstudio.com/resources/cheatsheets/), and [a template for their cheatsheets](http://www.rstudio.com/resources/cheatsheets/how-to-contribute-a-cheatsheet/) - but you have to create/edit them in keynote or powerpoint. Would be good to have a html/css based template that can be used, and possibly included in a package. 

Correct me if I'm wrong on anything here y'all

context: started a cheatsheet for taxize https://github.com/ropensci/cheatsheets

**Comment by maelle** [comment]
Thank you!

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
