### ISSUE TITLE
College Scorecard data access

### ISSUE THREAD

**Issue by mbjones** [ropensci-archive/wishlist#18]
An R package that provides easy access to the data behind the College Scorecard, which was recently released by the government.  
- What will the package do?
  - Provide access to data on college costs, demographics, and salaries for graduates
- Relevant links (For e.g. API docs, related software)
  - API docs: https://collegescorecard.ed.gov/data/
- Are there other related software?
  - Web presentation of data from government: https://collegescorecard.ed.gov
- What is the target audience
  - R users with an interest in education, and education outcomes
- Do you need help with development or are just suggesting the idea?
  - Just suggesting the idea; sorry, I don't have the cycles myself, but maybe someone would be interested
- what are some potential use cases?
  - Summarize trends across colleges (the government site only provides college-by-college stats)
  - Use college cost data for research, especially on relationship of educational outcomes
  - Build shiny apps to help explore the data

**Comment by Ironholds** [comment]
Looks cool!

**Comment by Ironholds** [comment]
Now going to start working on under the name "academiar"

**Comment by sckott** [comment]
@Ironholds did you start this, can't find it on github

**Comment by Ironholds** [comment]
I started but became overwhelmed and gave up :(. Sorry I didn't update here!

**Comment by sckott** [comment]
no worries

**Comment by Famguy** [comment]
@sckott Is this being done by anybody? I would like to volunteer for this in case nobody's working on it.

**Comment by sckott** [comment]
Nobody is working on it that I know of

**Comment by sckott** [comment]
@Famguy did you start working on this?

**Comment by Famguy** [comment]
@sckott Thanks for reminding me. Yes, I did start it but I got busy with some other things and couldn't finish it. I'll get back to working on it. 

In the meanwhile, I made another [package](https://github.com/Famguy/rgoodreads) which I want to submit to rOpenSci. Could you tell me what's the procedure to do it?

**Comment by sckott** [comment]
You can submit to our onboarding repo by opening a new issue https://github.com/ropensci/onboarding/issues/new

**Comment by juliasilge** [comment]
I was just looking at the College Scorecard data, and it appears there is an R package for accessing it by @btskinner:
https://github.com/btskinner/rscorecard
Already on CRAN as well:
https://cran.r-project.org/web/packages/rscorecard/index.html

**Comment by btskinner** [comment]
Hi everyone. I put together the [rscorecard](https://github.com/btskinner/rscorecard/) package that @juliasilge mentioned. Happy to answer any questions and/or take suggestions for improvements.

**Comment by maelle** [comment]
Thank you!

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
