### ISSUE TITLE
protein data bank web services

### ISSUE THREAD

**Issue by sckott** [ropensci-archive/wishlist#19]
- What will the package do?

A client for getting data from the RCSB protein data bank 
- Relevant links (For e.g. API docs, related software)

http://www.rcsb.org/pdb/software/rest.do
- Are there other related software?

not that I know of
- What is the target audience

molecular/cellular/evolutionary biologists
- Do you need help with development or are just suggesting the idea?

Suggesting
- what are some potential use cases?

Not sure as this isn't an area I know anything about...

**Comment by sckott** [comment]
Someone in this discipline would be an ideal maintainer

**Comment by cboettig** [comment]
Presumably there's stuff on Bioconductor already that does this?  A quick look suggests that Rcpi and QuartPAC have functions that might already be hitting that API: 
- https://www.bioconductor.org/packages/3.3/bioc/vignettes/Rcpi/inst/doc/Rcpi.pdf
- https://www.bioconductor.org/packages/3.3/bioc/manuals/QuartPAC/man/QuartPAC.pdf

Anyway, like you say, would need someone in the discipline to assess the situation.

**Comment by sckott** [comment]
Good point, forgot to look at Biocondctor!

**Comment by Ironholds** [comment]
Already did it - https://github.com/Ironholds/protein

I'm _not_ in the discipline, so patches cleaning up descriptions or adding functionality are great :)

**Comment by maelle** [comment]
Thank you!

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
