### ISSUE TITLE
Workflow for editing wiki

### ISSUE THREAD

**Issue by cboettig** [ropensci-archive/wishlist#2]
I've added an additional comment to @Ironholds's excellent suggestion regarding RDF and RDFA.  I wasn't sure what the best workflow to go about this was though.  In particular, we want a workflow for these kind of edits where the original proposer can see comments about existing packages, etc and decide how best to modify their description. (Sure, I as the later editor of the wiki page could try and guess how it does / doesn't fit in, but that's not ideal). I tried tagging @ironholds in the commit message -- not sure if that works on wikis.  

Anyway, perhaps the README can clarify some of the workflow here?

**Comment by Ironholds** [comment]
I didn't see the ping, so I don't think it works. Womp womp :(. Ideas for what the workflow should look like? I'm open to any suggestions :). Just off the top of my head, we could use issues to discuss specific things with specific proposals (one issue for "volunteer to help with [project], which doesn't have a repo yet", or something)

**Comment by cboettig** [comment]
Yeah, I'm just not sure the wiki is really the right workflow for this.  Maybe all requests should be filed as issues instead, and they can be updated as the work progresses and closed as when the feature is done? (facilitating #3 as well)

I think this is basically a collection of (rather large) "feature requests", and I think the Github issues tracker works a bit better for that kind of thing than a wiki does.  (Also in identifying really active 'requests', tagging (e.g. 'wontfix', 'priority', 'new', 'update', 'extend'), milestoning them, facilitating dialog etc).  

What do you think about just using the issues tracker instead of the wiki for these requests?

**Comment by Ironholds** [comment]
I think that makes a lot of sense! @karthik thoughts?

**Comment by karthik** [comment]
> I tried tagging @ironholds in the commit message -- not sure if that works on wikis.

Unfortunately it doesn't work for the wiki git repo. I made some workflow comments in #3.

**Comment by jennybc** [comment]
I am anti-GitHub wiki for these sorts of reasons. Poorly integrated with everything else.

**Comment by Ironholds** [comment]
@jennybc is that a vote for "the wiki as a status store, the issues to discuss"?

**Comment by leeper** [comment]
I agree with @cboettig that issues would be the way to go for this. I think it also then needs a firm commitment from one or more people to actively mod the repo.

**Comment by Ironholds** [comment]
Happy to give that commitment!

**Comment by cboettig** [comment]
@leeper @Ironholds @karthik Just a ping here since this issue is still open and the README is still directing people to add suggestions on the wiki page; though it looks like we are also getting suggestions on the issues page.  

Shall we go ahead and update the README to point users to the issues list instead?  Looks like some of the requests on the wiki might need to be migrated to issues as well.  

(Happy to assist but didn't want to forge ahead changing things)

**Comment by Ironholds** [comment]
No problem at my end!

**Comment by leeper** [comment]
:+1:

**Comment by cboettig** [comment]
looks like we still have some really good ideas on the Wiki that aren't copied over to issues.  Could we port them over to issues so that we can have a bit more discussion thread and keep them in the same place?

**Comment by karthik** [comment]
I was thinking the same. Let's do it.
