### ISSUE TITLE
algaebase

### ISSUE THREAD

**Issue by jsta** [ropensci-archive/wishlist#20]
I would like to submit my wish for an [algaebase](http://algaebase.org/) package as a follow-on to [rfishbase](https://github.com/ropensci/rfishbase). My specific interest is in scripted retrieval of the place names listed under the **common names** field of each species entry. Another use-case might be retrieving [author citations](https://en.wikipedia.org/wiki/Author_citation_%28zoology%29). I can see that some of the taxonomic functionality of algaebase might be superseded by the **taxize** package.

**Comment by karthik** [comment]
Hi @jsta 
This is the wrong repo. You should submit from the onboarding one.

**Comment by jsta** [comment]
Hmm, the way I interpret the README(s) is that the onboarding repo is for existing packages and the wishlist repo is for ideas? This is an idea....

**Comment by karthik** [comment]
Ok got it. I misread that you already wrote this. Pinging @sckott for input.

**Comment by sckott** [comment]
Thanks for the issue @jsta  See also ropensci/taxize#433 where we discuss a bit using it for taxonomic data.  We don't have a connection to algaebase itself in `taxize`, but it sounds like at least taxonomic data from algebase may be in worms. I'm not positive though. 

For non-taxonomic data, it makes sense to have a separate client for algebase data. Do you know of a way to get at the data?

**Comment by sckott** [comment]
@jsta Any thoughts on:

> For non-taxonomic data, it makes sense to have a separate client for algebase data. Do you know of a way to get at the data?

**Comment by jsta** [comment]
@sckott See the discussion in https://github.com/ropensci/taxize/issues/433

**Comment by sckott** [comment]
woops, sorry, so does this https://github.com/ropensci/taxize/issues/433#issuecomment-167071651 mean that we should close this issue OR is there some data you can still get?

**Comment by sckott** [comment]
@jsta last comment

**Comment by jsta** [comment]
Yes, I think we should close. I hope to find a more open project to contribute my records.

**Comment by sckott** [comment]
okay, will do
