### ISSUE TITLE
movebank

### ISSUE THREAD

**Issue by TAlexPerkins** [ropensci-archive/wishlist#21]
data repository for animal tracking data

https://www.movebank.org

**Comment by sckott** [comment]
Good idea @TAlexPerkins - sorry about no reply 

do you use it much. in the time since your post did anything happen?

**Comment by Stan125** [comment]
Hi there, I'm interested in working on this. Can you tell a total newbie more about what the package would provide? Would the utility be to access the public database, or to connect to the data uploaded with your own account?

**Comment by sckott** [comment]
actually, it looks like there may already be an R client for movebank https://www.movebank.org/node/5919 and https://cran.r-project.org/web/packages/move/index.html - It looks like it's relatively recently updated as well

I'm not familiar with Movebank, so perhaps there are things not covered by that pkg

**Comment by cboettig** [comment]
Hey @TAlexPerkins ,

I was just looking at movebank to get some spatial data for my class (don't really know what I want to do with it, so definitely looking for suggestions).  

Anyway, I found the `move` package a bit frustrating, adds a lot of dependencies and doesn't really expose all of the underlying data (well, does better if you just use the `getMovebank` method with the entity type name and ignore all the other methods).  Though the more underlying problem for me is inconsistencies in the data itself (e.g. in whether or not I can actually download data that is flagged as `i_can_see_data`).  

I've put some notes here for comparison: https://github.com/cboettig/movebank . See README.Rmd, the R package bit itself just does a lightweight and a bit more error-safe version of `getMovebank` to call the API directly, so it's a bit easier to see how the R function relates to the commands given in the API docs: https://github.com/movebank/movebank-api-doc/blob/master/movebank-api.md

Just me fiddling for the moment, but might try and follow up with the admins about what's going on with this data.

**Comment by maelle** [comment]
Thank you!

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
