### ISSUE TITLE
Website seems not to be working

### ISSUE THREAD

**Issue by diogoprov** [ropensci-archive/wishlist#23]
I've trying to access stbase.org since I saw the PLoS One paper and I couldn't. I know it's in Portuguese, but take a look at the screen shot. I tried with Safari, Chrome, and Mozilla.

![sem titulo](https://cloud.githubusercontent.com/assets/5214836/15255559/0695e678-1913-11e6-89a5-6ceb705bfb2e.jpeg)

Any thoughts?

Thank you in advance

**Comment by sckott** [comment]
where's the PLOS paper?

**Comment by diogoprov** [comment]
Sorry, I was talking about the STBase and I saw the [entry ](https://github.com/ropensci/wishlist/wiki/STBase-%28phylogenetic-tree-database%29)in the Wiki and I thought perhaps you were part of the project

**Comment by sckott** [comment]
ah, looks like @bomeara added that entry - Brian, know anything about this? Did they change URL ?

**Comment by bomeara** [comment]
That research group had a server go down ~ a month ago -- seems it's not back up. Makes this a far lower priority for ropensci...

**Comment by diogoprov** [comment]
Thanks for clarififying that Brian

**Comment by maelle** [comment]
Thank you!

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
