### ISSUE TITLE
Subversion API bindings: svn2r

### ISSUE THREAD

**Issue by billdenney** [ropensci-archive/wishlist#24]
While many people work with git, access to other version control software from R could help.  In my wishlist, I'd like to see a subversion R package that would work similarly to git2r.
- What will the package do?

> Link to the subversion library and enable direct access to subversion for tasks like: checkout, update, commit, branch, add, delete, extract logs.
- Relevant links (For e.g. API docs, related software)  

> https://subversion.apache.org/
- Are there other related software?  

> git2r, subversion
- What is the target audience  

> Software developers in R.  Anyone needing access to subversion for version control.
- Do you need help with development or are just suggesting the idea?  

> Help with development (with basic C++ bindings)
- What are some potential use cases?  

> For reproducible research, control data, code, and reports in a subversion archive.

**Comment by sckott** [comment]
Would you be able to be maintainer/lead development?

**Comment by billdenney** [comment]
Unfortunately not.  I don't work in C enough to make the language bindings.  I'm very able to help with the R side of the coding, use cases, tests, etc.

**Comment by sckott** [comment]
Okay. 

I'll post this on our community forum to see if there's any interest 

posted at https://discuss.ropensci.org/t/subversion-client/376

**Comment by maelle** [comment]
Thank you!

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
