### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by baptiste** [ropensci-archive/wishlist#26]
Frequently Asked Questions (FAQs) can be a very useful resource for quick answers, but I'm not aware of an R package to facilitate their storage, publication, and convenient dissemination. The official [R FAQ](https://cran.r-project.org/doc/FAQ/R-FAQ.html#Obtaining-this-document) is in my opinion underused because difficult to access, browse, or extend (texinfo source). Few packages provide their own FAQ, with no standardised format or location.

I have posted a couple of suggestions or [questions about this](http://stackoverflow.com/questions/10763402/faq-markup-to-r-data-structure) with some interesting answers, but never got very far. With the recent changes around CRAN, R, github, markdown, revisiting this idea might produce something useful to the community.

**Comment by sckott** [comment]
Good idea @baptiste - What do you think is the ideal form FAQ would take in an R package?

**Comment by maelle** [comment]
Thank you!

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
