### ISSUE TITLE
Package to search CITES information for species and higher taxon

### ISSUE THREAD

**Issue by FVFaleiro** [ropensci-archive/wishlist#29]
**1 - What will the package do?**
The package could be able to retrieve information about appendices of CITES (https://cites.org/) for each species or other taxonomic level and could inform 
**2 - Relevant links (For e.g. API docs, related software)**
The http://checklist.cites.org/#/en and https://www.speciesplus.net/species have the options to search for these informations, but do not have option for many species. 
**3 - Are there other related software?**
The package could works like the rredlist and taxize packages. 
**4 - What is the target audience**
The CITES (the Convention on International Trade in Endangered Species of Wild Fauna and Flora) have usefull information about restrictions of species trade and it is important for many political decisions about species conservation. It can be used by any user interested in use the CITES information like environmental protection agency, scientists, conservationists, environment organizations, educators, students, government. etc
**5 - Do you need help with development or are just suggesting the idea?**
I am suggesting the idea.
**6 - What are some potential use cases?**
Retrieve the CITES information for a list of species or other taxonomic level. The package could be able to deal with any taxonomic level, because the appendices of CITES have some category both to species and other higher taxonomy like the Primates order. The package could be able to deal with synonyms.

**Comment by sckott** [comment]
thanks for opening the issue @FVFaleiro 

- api docs: http://api.speciesplus.net/

**Comment by ibartomeus** [comment]
Hi Sckott, we are starting this at EAB meeting hackathon: https://github.com/ibartomeus/citesr

**Comment by ibartomeus** [comment]
See http://joss.theoj.org/papers/10.21105/joss.01091 I think the issue can be closed now :)

**Comment by maelle** [comment]
@goldingn look a package born at the EAB meeting hackathon!

**Comment by maelle** [comment]
Software peer-review thread https://github.com/ropensci/onboarding/issues/244

Current package URL https://github.com/ropensci/rcites

Thanks @ibartomeus for the update and congrats to you and the other authors!
