### ISSUE TITLE
R package to interact with Open Science Framework (OSF)

### ISSUE THREAD

**Issue by hafen** [ropensci-archive/wishlist#30]
@chartgerink has written a nice R package, [osfr](https://github.com/chartgerink/osfr), for interacting with the [Open Science Framework](https://osf.io/) (OSF). OSF fits in nicely with ROpenSci's mission, providing a free platform for sharing open and reproducible data, code, and results for scientists to make public as a companion to publications or ongoing scientific work.

- What does the package do: osfr provides an R interface to OSF, allowing users to upload and download files to and from OSR, among several other operations.
- Relevant links: https://github.com/chartgerink/osfr
- Other related software: There are some other platforms that have similar functionality, such as synapse.org.
- Target audience: R users working on open science projects who want a programmatic way to deploy results to OSF.

**Comment by chartgerink** [comment]
@karthik we communicated way back about this in 2015; my apologies for not having more developed sooner. I committed and didn't deliver.

I'll be checking out the developments of [`osf-cli`](https://github.com/dib-lab/osf-cli) and incorporating functions as I come across them. I might be renaming some of the canonical functions for parsimony if desirable. That would increase ease-of-use across platforms.

Are there any specific features that rOpenSci would want included for inclusion on the list? Feel free to drop them here and I'll incorporate them as good as I can.

**Comment by karthik** [comment]
Hi @chartgerink 
I'm just seeing this thread. No worries on the delay (I'm guilty of this myself). There are several users in the rOpenSci community that rely heavily on OSF, but I don't quite know their needs and challenges. It would be great if you were to start a thread on discuss.ropensci.org so we can get more input (our community manager will reach out to that segment).

**Comment by benmarwick** [comment]
This package has now been released here: https://github.com/CenterForOpenScience/osfr Hooray! And thanks to @aaronwolen and @chartgerink !

**Comment by aaronwolen** [comment]
Thanks, @benmarwick! We're planning to submit to ropensci for code review in the next week or so and hope to be on CRAN shortly thereafter. Let me know if you get a chance to check it out and have any feedback.

**Comment by stefaniebutland** [comment]
Here's the peer-reviewed result! https://docs.ropensci.org/osfr/

And the [review thread](https://github.com/ropensci/software-review/issues/279), with thanks to Heidi Seibold and Carl Boettiger for reviewing.

**Comment by maelle** [comment]
Thank you!

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
