### ISSUE TITLE
UK worldpop API package #SODD

### ISSUE THREAD

**Issue by hrbrmstr** [ropensci-archive/wishlist#32]
Ref: https://stackoverflow.com/a/48486531/1457051

Site: http://www.worldpop.org.uk/data/ # NOTE: newer firefox (right) prevents loading of some javascript files due to the site specifying a wrong sha hash. need to use older ffox, chrome or safari

The site is a total pain to work with interactively and programmatically, but it has (AFAICanTell) decent, useful data and they don't prohibit scraping (only automated searching).

The code at the SO answer URL shld also provide a good starting point for any budding 📦 developer.

### What will the package do?

Enable finding of and retrieval of datasets from http://www.worldpop.org.uk/data/

### Relevant links (For e.g. API docs, related software)

- http://www.worldpop.org.uk/data/
- https://stackoverflow.com/a/48486531/1457051

### Are there other related software?

This seems to be a "unique-ish" data compilation, so it's unlikely duplicated anywhere else (for the types of data it has)

### What is the target audience

Any scientist who needs gridded (or other) detailed global population data

### Do you need help with development or are just suggesting the idea?

suggesting the idea and linked to some starter code

### What are some potential use cases?

- http://www.worldpop.org.uk/data/methods/
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5518145/

**Comment by KKulma** [comment]
Has there been any development on this?

**Comment by maelle** [comment]
Thank you!

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
