### ISSUE TITLE
EpiCollect API client

### ISSUE THREAD

**Issue by noamross** [ropensci-archive/wishlist#33]
[EpiCollect5](https://five.epicollect.net/) is a pretty handy tool for building field data collection apps and storing the data online.  Projects have read-only APIs to retrieve data and project metadata, accessed by a app-specific tokens that you set up.  

Docs are reasonable: https://epicollect5.gitbooks.io/epicollect5-api/content/, https://epicollect5.gitbooks.io/epicollect5-user-guide

Since every project will have its own data structure, it seems like an R6-type API project.  Pagination support would be nice.

@richfitz, do you have any association with this?

**Comment by noamross** [comment]
Some prior art: https://gist.github.com/mirko77/3f4a101cd4a77e2ae3e760d44d18d901

**Comment by maelle** [comment]
Thank you!

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
