### ISSUE TITLE
What should go in contributions.md?

### ISSUE THREAD

**Issue by karthik** [ropensci-archive/wishlist#5]
To add a new package to the wish list, follow this template
1. What will the package do?
2. Relevant links (For e.g. API docs, related software)
3. Are there other related software?
4. What is the target audience
5. Do you need help with development or are just suggesting the idea?

Once you have filed an issue with as much detail answering these questions, edit the wiki page and add a link under the appropriate category with a link to your issue.

**Comment by karthik** [comment]
@Ironholds what else should we add?

**Comment by Ironholds** [comment]
I guess "what are the use cases?" unless that's covered by target audience? Other than that it looks pretty solid to me.

**Comment by maelle** [comment]
Thank you!

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
