### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by karthik** [ropensci-archive/wishlist#7]
@Ironholds I added a few labels so we can appropriately tag and filter incoming requests. Any others we should cover?

PS, if you use [command like gh issues](https://github.com/stephencelis/ghi), it's easy to programmatically add more labels like so:

```
ghi label -a api-package -c #2c3e50
ghi label -a geo-package -c #f39c12
ghi label -a urgent -c  #c0392b
ghi label -a collaborators_wanted -c #27ae60
```

**Comment by Ironholds** [comment]
I guess a "meta" tag for "how the heck does this wishlist work?" ;).

You might also consider:
1. "library-exists": "there is a C or C++ library we can pull in as a backend"
2. "template-exists" "there isn't a C or C++ library we can pull in but Scott found this one ruby package that does exactly this and we should replicate their functionality"

**Comment by leeper** [comment]
Maybe call (2) "port-opportunity" or something.

**Comment by karthik** [comment]
@Ironholds done
@leeper good idea, added.
