### ISSUE TITLE
Client for Open Access Button API

### ISSUE THREAD

**Issue by jshoyer** [ropensci-archive/wishlist#8]
1. What will the package do?
   - Allow one to programmatically access data from the Open Access Button site,
     and perhaps integrate this data with other rOpenSci tools
2. Relevant links
   - https://openaccessbutton.org/about#how
     - Page also includes FAQ
   - API: http://oabutton.cottagelabs.com/docs
     - NB: in spite of the URI for this page,
       the project prefers that the initialism 'OA' not be used when referring to 'the button'.
       See 'Style request' at the button of [about#press](https://openaccessbutton.org/about#press) tab.
3. Does other related software exist?
   - I am unaware of any wrappers for the API, but have not looked carefully
4. What is the target audience?
   - Librarians, button users, open access advocates
5. Do you need help with development or are just suggesting the idea?
   - I am mainly suggesting the idea.
     I do not quite understand the javascript on the API page linked above,
     so I have not been able to make a start on this.
6. What are some potential use cases?
   - In principle, using the button is preferable to #IcanHazPDFing, using interlibrary loan, or buying single articles.
     One can imagine using such a package to facilitate bibliometric text mining,
     identifying journals where researchers at a given institution frequently hit paywalls,
     or even identifying researchers that are failing to comply with open access/archiving mandates.

**Comment by Ironholds** [comment]
Perhaps it'd be good to explain what the Open Access Button site does?

**Comment by jshoyer** [comment]
The Open Access Button allows one to report journal article paywalls when one hits them. In theory the team will help you legally gain a copy of the article. However, no article on my wishlist has ever been retrieved, so I cannot tell if they actually do this. I no longer recommend the button to anyone, sadly.

There seems to be little demand for programmatic access to this kind of data, so I am closing this issue. Feel free to reopen it.
