### ISSUE TITLE
Client for Etherpad API

### ISSUE THREAD

**Issue by noamross** [ropensci-archive/wishlist#9]
Probably not the highest priority, but could be fun.

Uses:
1.  Pulling in data generated in collaboratively using YAML, TOML, or ArchieML
2.  Navel-gazing: Analyzing workshop participation

API Docs http://etherpad.org/doc/v1.5.1/

**Comment by richfitz** [comment]
:+1:

**Comment by maelle** [comment]
Thank you!

Note that future ideas should go to our [wishlist forum category](https://discuss.ropensci.org/c/wishlist/6).
